# Generated by Django 2.0.1 on 2019-07-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixintest', '0004_auto_20190711_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='biz',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
