# Generated by Django 2.0.1 on 2019-07-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixintest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
