# Generated by Django 2.0.1 on 2019-07-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixintest', '0002_data_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='html',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
    ]
