# Generated by Django 2.0.1 on 2019-07-11 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixintest', '0003_auto_20190710_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
