# Generated by Django 2.0 on 2020-04-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixintest', '0005_data_biz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jianxiangdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField()),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'weixin_jj',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
